#!/usr/bin/env -S just --justfile
# ^ A shebang isn't required, but allows a justfile to be executed
#   like a script, with `./justfile test`, for example.

set windows-shell := ["powershell.exe", "-NoLogo", "-Command"]
set dotenv-load := true

# Show available commands
default:
    @just --list --justfile {{justfile()}}

# Deploy this rust component
deploy:
    wash app deploy wadm.yaml

# Build this rust component
build:
    wash build

# Undeploy the rust actor
undeploy:
    wash app undeploy rust-http-hello-world && wash app delete rust-http-hello-world --delete-all
    wash stop actor http-hello-world-rust

# Build the rust component
build:
    wash build

# Cleans the built files of the rust
clean:
    rm -rf gen/*
