# This docker-compose file starts an entire wasmCloud ecosystem, including:
#   a NATS server
#   a local OCI registry
#   grafana + prometheus + tempo for metrics and tracing
#   a wasmCloud host
#   a WADM server for managing applications

version: "3"
services:
  nats:
    image: nats:2.10-alpine
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
      - "4001:4001"
    command:
      - "-c=/etc/nats/nats-server.conf"
    volumes:
      - ./config/nats.conf:/etc/nats/nats-server.conf

  tempo:
    image: grafana/tempo:2.3.1
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./config/tempo.yaml:/etc/tempo.yaml
    ports:
      - 4318:4318 # otlp http
      - 7999:7999 # tempo

  loki:
    image: grafana/loki:2.9.4
    command:
      - "-config.file=/etc/loki/config.yaml"
    volumes:
      - ./config/loki.yaml:/etc/loki/config.yaml
    ports:
      - 3100:3100
    restart: unless-stopped

  registry:
    image: registry:2.8
    ports:
      - "5000:5000"

  grafana:
    image: grafana/grafana:10.0.10
    ports:
      - 5050:3000
    volumes:
      - ./config/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    depends_on:
      - prometheus
      - tempo

  prometheus:
    image: prom/prometheus:v2.49.1
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-remote-write-receiver"
      - "--enable-feature=native-histograms"
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yml

  wasmcloud:
    depends_on:
      - "nats"
      - "tempo"
    image: wasmcloud/wasmcloud:latest
    environment:
      RUST_LOG: debug,hyper=info,async_nats=info,oci_distribution=info,cranelift_codegen=warn
      WASMCLOUD_LOG_LEVEL: debug
      WASMCLOUD_RPC_HOST: nats
      WASMCLOUD_CTL_HOST: nats
      WASMCLOUD_ALLOW_FILE_LOAD: "true"
      WASMCLOUD_OCI_ALLOWED_INSECURE: registry:5000
      WASMCLOUD_OBSERVABILITY_ENABLED: "true"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4318/v1/traces
    ports:
      - "8000-8070:8000-8070"

  wadm:
    depends_on:
      - "nats"
    image: ghcr.io/wasmcloud/wadm:latest
    environment:
      - WADM_NATS_SERVER=nats
