name = "http-hello-world-go"
language = "tinygo"
type = "actor"
version = "0.1.0"

[actor]
wit_world = "hello-go"
wasm_target = "wasm32-wasi-preview2"
destination = "../build/http_hello_world_go.wasm"
